name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
       os: [macos-latest, ubuntu-18.04]
       include:
         - os: ubuntu-18.04
           buildTest: "swift build -v"
           runTest: "swift test -v"
         - os: macos-latest
           buildTest: "swift package generate-xcodeproj"
           runTest: "xcodebuild test"
    steps:
      - uses: fwal/setup-swift@v1.4.0
        if: ${{ matrix.os != 'macos-latest'}}
      - uses: actions/checkout@v2
      - name: PackagesResolve
        run: swift package resolve
      - name: Build
        run: swift build -v
      - name: Run Test.sh
        run: bash Test.sh
      - name: Build tests
        env:
          BUILDTEST: ${{ matrix.buildTest }}
        run: $BUILDTEST
      - name: Run tests
        env:
          RUNTEST: ${{ matrix.runTest }}
        run: $RUNTEST

