name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: PackagesResolve
      run: swift package resolve
    - name: Build
      run: swift build -v
    - name: Build tests
      run: swift build --build-tests
    - name: Run tests
      run: swift test -v
    - name: Run Test.sh
      run: Test.sh
