name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Swift
      uses: fwal/setup-swift@v1.3.0
    - uses: actions/checkout@v2
    - name: PackagesResolve
      run: swift package resolve
    - name: Build
      run: swift build -v
    - name: Run Test.sh
      run: bash Test.sh
    - name: Build tests
      run: swift build --build-tests
    - name: Run tests
      run: swift test -v
